### ISSUE TITLE
antq command not found - exit code 127

### ISSUE THREAD

**Issue by practicalli-johnny** [liquidz/antq-action#3]
When running Antq with a GitHub workflow, an error message states that `antq` command was not found and returns an exit code 127.  This has happened on several repositories, although some [repositories antq is listing libraries to update](https://github.com/practicalli/clojure-cli-config/actions/runs/4868215018).

Running Antq on the command line for the same project locally (using a Clojure CLI alias) reports "All dependencies are up-to-date"

The workflow failures are all on repositories that do not have libraries or GitHub actions to update (although this may be a coincidence).

I have also run the antq workflow manually from a workflow_dispath: setting, to check if it was a timing issue, but [the manual run also fails](https://github.com/practicalli/clojure-service-template/actions/runs/4872091502/jobs/8689849450)

Any suggestions as to why the antq workflow is failing for one repository and not another?

## GitHub workflow output
Output from running the GitHub workflow via a scheduled job [workflow logs](https://github.com/practicalli/clojure-service-template/actions/runs/4857538261/jobs/8658118594)

```shell
0s
Run antq --error-format="::error file={{file}}::{{message}}"
  antq --error-format="::error file={{file}}::{{message}}"
  shell: /usr/bin/bash -e {0}
/home/runner/work/_temp/8c6[1](https://github.com/practicalli/clojure-service-template/actions/runs/4857538261/jobs/8658118594#step:9:1)833b-d8[2](https://github.com/practicalli/clojure-service-template/actions/runs/4857538261/jobs/8658118594#step:9:2)b-[4](https://github.com/practicalli/clojure-service-template/actions/runs/4857538261/jobs/8658118594#step:9:5)aa2-82fd-af[5](https://github.com/practicalli/clojure-service-template/actions/runs/4857538261/jobs/8658118594#step:9:6)c4f8b01c6.sh: line 1: antq: command not found
Error: Process completed with exit code 127.
```

## GitHub workflow configuration

```yaml
name: "Scheduled Version Check"
on:
  schedule:
    - cron: "0 4 * * *" # at 04:04:04 ever day
    # - cron: "0 4 * * 5" # at 04:04:04 ever Friday
    # - cron: "0 4 1 * *" # at 04:04:04 on first day of month
  workflow_dispatch: # Run manually via GitHub Actions Workflow page

jobs:
  scheduled-version-check:
    name: "Scheduled Version Check"
    runs-on: ubuntu-latest
    steps:
      - run: echo "🚀 Job automatically triggered by ${{ github.event_name }}"
      - run: echo "🐧 Job running on ${{ runner.os }} server"
      - run: echo "🐙 Using ${{ github.ref }} branch from ${{ github.repository }} repository"

      - name: "Checkout code"
        uses: actions/checkout@v3
      - run: echo "🐙 ${{ github.repository }} repository was cloned to the runner."

      - name: "Setup Antq"
        uses: liquidz/antq-action@main

      - name: "Antq Check versions"
        run: antq --error-format="::error file={{file}}::{{message}}"

      - run: echo "🎨 library versions checked with liquidz/antq"

      - run: echo "🍏 Job status is ${{ job.status }}."
```
